use clientidb;
create table Clienti (
	id INT,
	nome VARCHAR(50),
	cognome VARCHAR(50),
	email VARCHAR(50),
	eta INT,
	citta VARCHAR(50)
);



insert into Clienti (id, nome, cognome, email, eta, citta) values (1, 'Andy', 'Tabbernor', 'atabbernor0@ca.gov', 83, 'Baratleke');
insert into Clienti (id, nome, cognome, email, eta, citta) values (2, 'Theodore', 'Esposi', 'tesposi1@squarespace.com', 75, 'Haozhai');
insert into Clienti (id, nome, cognome, email, eta, citta) values (3, 'Cicely', 'Humphries', 'chumphries2@wikia.com', 43, 'Didou');
insert into Clienti (id, nome, cognome, email, eta, citta) values (4, 'Milton', 'Bride', 'mbride3@baidu.com', 73, 'Krajan Sumberanget');
insert into Clienti (id, nome, cognome, email, eta, citta) values (5, 'Doyle', 'Paolo', 'dpaolo4@shinystat.com', 89, 'Konstantynów Łódzki');
insert into Clienti (id, nome, cognome, email, eta, citta) values (6, 'Ozzy', 'Kloska', 'okloska5@senate.gov', 43, 'Grati Satu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (7, 'Kaylil', 'Cod', 'kcod6@geocities.jp', 23, 'Sarāvān');
insert into Clienti (id, nome, cognome, email, eta, citta) values (8, 'Celinda', 'Goundrill', 'cgoundrill7@slashdot.org', 21, 'Siva');
insert into Clienti (id, nome, cognome, email, eta, citta) values (9, 'Emmet', 'Simpson', 'esimpson8@china.com.cn', 63, 'Vannes');
insert into Clienti (id, nome, cognome, email, eta, citta) values (10, 'Hyacinthe', 'Jardein', 'hjardein9@arizona.edu', 64, 'Hujiaying');
insert into Clienti (id, nome, cognome, email, eta, citta) values (11, 'Ax', 'Espinho', 'aespinhoa@ucla.edu', 89, 'Pingle');
insert into Clienti (id, nome, cognome, email, eta, citta) values (12, 'Hildagarde', 'Cowle', 'hcowleb@globo.com', 96, 'Alunda');
insert into Clienti (id, nome, cognome, email, eta, citta) values (13, 'Hymie', 'Awton', 'hawtonc@psu.edu', 36, 'Sélestat');
insert into Clienti (id, nome, cognome, email, eta, citta) values (14, 'Page', 'Bottrell', 'pbottrelld@wisc.edu', 44, 'Sishan');
insert into Clienti (id, nome, cognome, email, eta, citta) values (15, 'Courtnay', 'Ruste', 'crustee@edublogs.org', 49, 'Khayr Kōṯ');
insert into Clienti (id, nome, cognome, email, eta, citta) values (16, 'Nikkie', 'Border', 'nborderf@tinypic.com', 46, 'Nahariya');
insert into Clienti (id, nome, cognome, email, eta, citta) values (17, 'Tracy', 'Crutch', 'tcrutchg@cnn.com', 31, 'Bęczarka');
insert into Clienti (id, nome, cognome, email, eta, citta) values (18, 'Sharity', 'Pescud', 'spescudh@wikispaces.com', 56, 'Nuevo Chamelecón');
insert into Clienti (id, nome, cognome, email, eta, citta) values (19, 'Jessika', 'Lengthorn', 'jlengthorni@shinystat.com', 65, 'Miskolc');
insert into Clienti (id, nome, cognome, email, eta, citta) values (20, 'Martynne', 'Bolan', 'mbolanj@de.vu', 85, 'Bergen');
insert into Clienti (id, nome, cognome, email, eta, citta) values (21, 'Sheffy', 'Peaple', 'speaplek@liveinternet.ru', 30, 'Cunén');
insert into Clienti (id, nome, cognome, email, eta, citta) values (22, 'Masha', 'Lowres', 'mlowresl@com.com', 26, 'Sharm el-Sheikh');
insert into Clienti (id, nome, cognome, email, eta, citta) values (23, 'Sondra', 'Goodsal', 'sgoodsalm@google.it', 34, 'Blokdesa Situgede');
insert into Clienti (id, nome, cognome, email, eta, citta) values (24, 'Barbi', 'Tyrone', 'btyronen@google.nl', 53, 'Pertunmaa');
insert into Clienti (id, nome, cognome, email, eta, citta) values (25, 'Karrie', 'Pach', 'kpacho@soundcloud.com', 80, 'Caxarias');
insert into Clienti (id, nome, cognome, email, eta, citta) values (26, 'Josepha', 'Eustice', 'jeusticep@latimes.com', 43, 'Jalālpur');
insert into Clienti (id, nome, cognome, email, eta, citta) values (27, 'Biddy', 'Startin', 'bstartinq@globo.com', 78, 'Los Fresnos');
insert into Clienti (id, nome, cognome, email, eta, citta) values (28, 'Vivianna', 'Chatelet', 'vchateletr@toplist.cz', 57, 'Iwakuni');
insert into Clienti (id, nome, cognome, email, eta, citta) values (29, 'Alain', 'Tart', 'atarts@youku.com', 83, 'Mantes-la-Jolie');
insert into Clienti (id, nome, cognome, email, eta, citta) values (30, 'Cecily', 'Hame', 'chamet@yelp.com', 86, 'Longjumeau');
insert into Clienti (id, nome, cognome, email, eta, citta) values (31, 'Glynnis', 'Hunstone', 'ghunstoneu@whitehouse.gov', 91, 'Sibayo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (32, 'Micky', 'Renneke', 'mrennekev@google.es', 97, 'Gore');
insert into Clienti (id, nome, cognome, email, eta, citta) values (33, 'Carlyn', 'Keel', 'ckeelw@wordpress.com', 88, 'Non Sung');
insert into Clienti (id, nome, cognome, email, eta, citta) values (34, 'Hazlett', 'Stump', 'hstumpx@rakuten.co.jp', 73, 'Savé');
insert into Clienti (id, nome, cognome, email, eta, citta) values (35, 'Trueman', 'Birkwood', 'tbirkwoody@merriam-webster.com', 63, 'Aranguren');
insert into Clienti (id, nome, cognome, email, eta, citta) values (36, 'Baxie', 'Canedo', 'bcanedoz@mashable.com', 60, 'Penteado');
insert into Clienti (id, nome, cognome, email, eta, citta) values (37, 'Cynthie', 'Elijah', 'celijah10@newyorker.com', 34, 'Ōgaki');
insert into Clienti (id, nome, cognome, email, eta, citta) values (38, 'Anson', 'Flude', 'aflude11@shinystat.com', 86, 'Shtip');
insert into Clienti (id, nome, cognome, email, eta, citta) values (39, 'Lucienne', 'Rowlett', 'lrowlett12@artisteer.com', 93, 'Nagu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (40, 'Nevins', 'Fann', 'nfann13@smugmug.com', 42, 'Caijiapu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (41, 'Faith', 'Bradshaw', 'fbradshaw14@pagesperso-orange.fr', 64, 'Chinchero');
insert into Clienti (id, nome, cognome, email, eta, citta) values (42, 'Gayle', 'Stenett', 'gstenett15@technorati.com', 47, 'Sonorejo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (43, 'Demetris', 'Ditchfield', 'dditchfield16@dmoz.org', 51, 'Towa');
insert into Clienti (id, nome, cognome, email, eta, citta) values (44, 'Hermon', 'Pettingill', 'hpettingill17@senate.gov', 94, 'Rudnichnyy');
insert into Clienti (id, nome, cognome, email, eta, citta) values (45, 'Charisse', 'Badman', 'cbadman18@gmpg.org', 42, 'Bairro Assunção Piedade');
insert into Clienti (id, nome, cognome, email, eta, citta) values (46, 'Ivar', 'McKerrow', 'imckerrow19@unicef.org', 65, 'Quilo-quilo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (47, 'Chane', 'Sheal', 'csheal1a@mit.edu', 79, 'Peuhaq');
insert into Clienti (id, nome, cognome, email, eta, citta) values (48, 'Nedi', 'Hartzog', 'nhartzog1b@cbc.ca', 54, 'Villa Santa Rita');
insert into Clienti (id, nome, cognome, email, eta, citta) values (49, 'Crysta', 'Cundy', 'ccundy1c@craigslist.org', 29, 'Malšice');
insert into Clienti (id, nome, cognome, email, eta, citta) values (50, 'Tonya', 'Kenryd', 'tkenryd1d@163.com', 93, 'Hannover');
insert into Clienti (id, nome, cognome, email, eta, citta) values (51, 'Debee', 'Hexum', 'dhexum1e@time.com', 61, 'Wulong');
insert into Clienti (id, nome, cognome, email, eta, citta) values (52, 'Filberte', 'Beynon', 'fbeynon1f@disqus.com', 96, 'Rancaseneng');
insert into Clienti (id, nome, cognome, email, eta, citta) values (53, 'Branden', 'MacAlroy', 'bmacalroy1g@netscape.com', 29, 'Mežica');
insert into Clienti (id, nome, cognome, email, eta, citta) values (54, 'Adeline', 'Margrem', 'amargrem1h@ask.com', 26, 'Sumber Tengah');
insert into Clienti (id, nome, cognome, email, eta, citta) values (55, 'Currey', 'Hardingham', 'chardingham1i@google.ca', 27, 'Obispos');
insert into Clienti (id, nome, cognome, email, eta, citta) values (56, 'Abigael', 'Kingscote', 'akingscote1j@altervista.org', 75, 'Lindome');
insert into Clienti (id, nome, cognome, email, eta, citta) values (57, 'Wendi', 'Neads', 'wneads1k@sciencedaily.com', 64, 'Mochudi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (58, 'Ruby', 'Storks', 'rstorks1l@bloglovin.com', 70, 'Šmarje pri Jelšah');
insert into Clienti (id, nome, cognome, email, eta, citta) values (59, 'Kaile', 'Chasemoore', 'kchasemoore1m@seattletimes.com', 64, 'Mafang');
insert into Clienti (id, nome, cognome, email, eta, citta) values (60, 'Jorrie', 'Huntriss', 'jhuntriss1n@eventbrite.com', 48, 'Bongao');
insert into Clienti (id, nome, cognome, email, eta, citta) values (61, 'Joelle', 'Beesley', 'jbeesley1o@xrea.com', 78, 'Pertunmaa');
insert into Clienti (id, nome, cognome, email, eta, citta) values (62, 'Carrissa', 'Castellini', 'ccastellini1p@amazonaws.com', 74, 'Oslo');
insert into Clienti (id, nome, cognome, email, eta, citta) values (63, 'Bette', 'Spillman', 'bspillman1q@hibu.com', 71, 'Polzela');
insert into Clienti (id, nome, cognome, email, eta, citta) values (64, 'Read', 'Ciccerale', 'rciccerale1r@jigsy.com', 29, 'Lankaran');
insert into Clienti (id, nome, cognome, email, eta, citta) values (65, 'Helena', 'Sizzey', 'hsizzey1s@twitpic.com', 18, 'Göteborg');
insert into Clienti (id, nome, cognome, email, eta, citta) values (66, 'Ingar', 'Lintill', 'ilintill1t@wp.com', 89, 'Nevyts’ke');
insert into Clienti (id, nome, cognome, email, eta, citta) values (67, 'Sharl', 'Bollans', 'sbollans1u@furl.net', 68, 'Itatinga');
insert into Clienti (id, nome, cognome, email, eta, citta) values (68, 'Lynn', 'D''Ambrogi', 'ldambrogi1v@prnewswire.com', 39, 'Cikadu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (69, 'Estel', 'Leggis', 'eleggis1w@umich.edu', 37, 'Atlantis');
insert into Clienti (id, nome, cognome, email, eta, citta) values (70, 'Yankee', 'Pes', 'ypes1x@apache.org', 97, 'Ghouazi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (71, 'Jenn', 'Upson', 'jupson1y@ustream.tv', 18, 'Novodmitriyevskaya');
insert into Clienti (id, nome, cognome, email, eta, citta) values (72, 'Phyllys', 'Heckney', 'pheckney1z@cnbc.com', 77, 'Kolomyya');
insert into Clienti (id, nome, cognome, email, eta, citta) values (73, 'Prisca', 'Denson', 'pdenson20@chronoengine.com', 86, 'Caleufú');
insert into Clienti (id, nome, cognome, email, eta, citta) values (74, 'Leigh', 'Talby', 'ltalby21@fotki.com', 80, 'Nan');
insert into Clienti (id, nome, cognome, email, eta, citta) values (75, 'Pat', 'Robilart', 'probilart22@wordpress.com', 81, 'Chexi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (76, 'Dorie', 'Minett', 'dminett23@latimes.com', 72, 'Ozubulu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (77, 'Patty', 'Huntriss', 'phuntriss24@etsy.com', 97, 'Würzburg');
insert into Clienti (id, nome, cognome, email, eta, citta) values (78, 'Brinna', 'Cattach', 'bcattach25@sourceforge.net', 45, 'Solnechnoye');
insert into Clienti (id, nome, cognome, email, eta, citta) values (79, 'Nigel', 'Lindsey', 'nlindsey26@privacy.gov.au', 65, 'Vranje');
insert into Clienti (id, nome, cognome, email, eta, citta) values (80, 'Reuven', 'Balogun', 'rbalogun27@nhs.uk', 42, 'Ulcinj');
insert into Clienti (id, nome, cognome, email, eta, citta) values (81, 'Paule', 'Balsdone', 'pbalsdone28@huffingtonpost.com', 71, 'Älvdalen');
insert into Clienti (id, nome, cognome, email, eta, citta) values (82, 'Arabele', 'Jacobowitz', 'ajacobowitz29@deliciousdays.com', 80, 'Guanjiabao');
insert into Clienti (id, nome, cognome, email, eta, citta) values (83, 'Evaleen', 'Rainer', 'erainer2a@cnbc.com', 65, 'Chorente');
insert into Clienti (id, nome, cognome, email, eta, citta) values (84, 'Mady', 'Moyles', 'mmoyles2b@japanpost.jp', 93, 'Sinargalih');
insert into Clienti (id, nome, cognome, email, eta, citta) values (85, 'Ami', 'Iacoboni', 'aiacoboni2c@cnbc.com', 36, 'Kommunisticheskiy');
insert into Clienti (id, nome, cognome, email, eta, citta) values (86, 'Gilbertine', 'Yerborn', 'gyerborn2d@umich.edu', 79, 'Lagodekhi');
insert into Clienti (id, nome, cognome, email, eta, citta) values (87, 'Felita', 'Lewtey', 'flewtey2e@weebly.com', 80, 'Shnogh');
insert into Clienti (id, nome, cognome, email, eta, citta) values (88, 'Cora', 'Benes', 'cbenes2f@angelfire.com', 74, 'Vyaz’ma');
insert into Clienti (id, nome, cognome, email, eta, citta) values (89, 'Nicolis', 'Meiningen', 'nmeiningen2g@independent.co.uk', 81, 'Gramoteino');
insert into Clienti (id, nome, cognome, email, eta, citta) values (90, 'Claudell', 'Disman', 'cdisman2h@foxnews.com', 86, 'Gorodets');
insert into Clienti (id, nome, cognome, email, eta, citta) values (91, 'Zonda', 'Hamley', 'zhamley2i@independent.co.uk', 29, 'Tétouan');
insert into Clienti (id, nome, cognome, email, eta, citta) values (92, 'Philippine', 'Orchart', 'porchart2j@xinhuanet.com', 89, 'Santo Estêvão');
insert into Clienti (id, nome, cognome, email, eta, citta) values (93, 'Maia', 'Kurth', 'mkurth2k@huffingtonpost.com', 78, 'Timon');
insert into Clienti (id, nome, cognome, email, eta, citta) values (94, 'Kate', 'Hawken', 'khawken2l@joomla.org', 75, 'Buk');
insert into Clienti (id, nome, cognome, email, eta, citta) values (95, 'Horton', 'Rozenbaum', 'hrozenbaum2m@sina.com.cn', 63, 'Kista');
insert into Clienti (id, nome, cognome, email, eta, citta) values (96, 'Sharron', 'Calafato', 'scalafato2n@de.vu', 43, 'Liebu');
insert into Clienti (id, nome, cognome, email, eta, citta) values (97, 'Arnie', 'Sandars', 'asandars2o@ustream.tv', 38, 'Hevlín');
insert into Clienti (id, nome, cognome, email, eta, citta) values (98, 'Corrie', 'Geach', 'cgeach2p@fc2.com', 50, 'Fengsheng');
insert into Clienti (id, nome, cognome, email, eta, citta) values (99, 'Jefferson', 'Fattorini', 'jfattorini2q@psu.edu', 73, 'Aktogay');
insert into Clienti (id, nome, cognome, email, eta, citta) values (100, 'Nona', 'Hedau', 'nhedau2r@ocn.ne.jp', 83, 'Jamaica');

create table Clienti2 (
	id INT,
	nome VARCHAR(50),
	citta VARCHAR(50)
);
insert into Clienti2 (id, nome, citta) values (1, 'Alleyn Aindriu', 'Guadalupe');
insert into Clienti2 (id, nome, citta) values (2, 'Kaiser Khristoforov', 'Lais');
insert into Clienti2 (id, nome, citta) values (3, 'Margaretta Giannassi', 'Bazar-Korgon');
insert into Clienti2 (id, nome, citta) values (4, 'Karil Bambrugh', 'Buzet');
insert into Clienti2 (id, nome, citta) values (5, 'Guglielma O''Hone', 'Komsomolsk');
insert into Clienti2 (id, nome, citta) values (6, 'Alison Duckit', 'Meixian');
insert into Clienti2 (id, nome, citta) values (7, 'Dennie Littefair', 'Ptení');
insert into Clienti2 (id, nome, citta) values (8, 'Joshia Okroy', 'Uryupinsk');
insert into Clienti2 (id, nome, citta) values (9, 'Leia Endricci', 'Sicheng');
insert into Clienti2 (id, nome, citta) values (10, 'Torey Bousquet', 'Ulset');
insert into Clienti2 (id, nome, citta) values (11, 'Francisca Boughton', 'Bordeaux');
insert into Clienti2 (id, nome, citta) values (12, 'Hayes Beeck', 'Buawan');
insert into Clienti2 (id, nome, citta) values (13, 'Ivory Klagges', 'Binucayan');
insert into Clienti2 (id, nome, citta) values (14, 'Roy Chessman', 'Gemblengmulyo');
insert into Clienti2 (id, nome, citta) values (15, 'Dorelle Gumby', 'Malaga');
insert into Clienti2 (id, nome, citta) values (16, 'Dorthea Pennoni', 'Paris 09');
insert into Clienti2 (id, nome, citta) values (17, 'Roarke Rosel', 'Shorapani');
insert into Clienti2 (id, nome, citta) values (18, 'Gregg Badsey', 'Taiping');
insert into Clienti2 (id, nome, citta) values (19, 'Eal Grimolbie', 'Gines-Patay');
insert into Clienti2 (id, nome, citta) values (20, 'Kate Sallowaye', 'Apitong');
insert into Clienti2 (id, nome, citta) values (21, 'Aleen Ferrelli', 'Asopós');
insert into Clienti2 (id, nome, citta) values (22, 'Culley Gabey', 'Hengjie');
insert into Clienti2 (id, nome, citta) values (23, 'Lyndsie Latek', 'Lechinkay');
insert into Clienti2 (id, nome, citta) values (24, 'Davon Conwell', 'Timrå');
insert into Clienti2 (id, nome, citta) values (25, 'Maren Elphinston', 'Flagstaff');
insert into Clienti2 (id, nome, citta) values (26, 'Hollie Heald', 'Olival Basto');
insert into Clienti2 (id, nome, citta) values (27, 'Patsy Marcq', 'Hengshui');
insert into Clienti2 (id, nome, citta) values (28, 'Stefania Gilhooley', 'Komsomolets');
insert into Clienti2 (id, nome, citta) values (29, 'Marisa Masurel', 'Borzęta');
insert into Clienti2 (id, nome, citta) values (30, 'Elenore Zute', 'Doumen');
insert into Clienti2 (id, nome, citta) values (31, 'Dexter Shavel', 'Jinji');
insert into Clienti2 (id, nome, citta) values (32, 'Arnuad Legg', 'Were');
insert into Clienti2 (id, nome, citta) values (33, 'Jessy Kobke', 'Brloh');
insert into Clienti2 (id, nome, citta) values (34, 'Corina McCart', 'Coromandel');
insert into Clienti2 (id, nome, citta) values (35, 'Gearalt Forstall', 'Maripa');
insert into Clienti2 (id, nome, citta) values (36, 'Barnabe Jerosch', '‘Anātā');
insert into Clienti2 (id, nome, citta) values (37, 'Carrol Carmody', 'Tianjiaba');
insert into Clienti2 (id, nome, citta) values (38, 'Daren Bills', 'Ordóñez');
insert into Clienti2 (id, nome, citta) values (39, 'Berthe Dymond', 'Kharagauli');
insert into Clienti2 (id, nome, citta) values (40, 'Dyann McCart', 'Shāhīn Dezh');
insert into Clienti2 (id, nome, citta) values (41, 'Wheeler MacCracken', 'Sukowiryo');
insert into Clienti2 (id, nome, citta) values (42, 'Kriste Elstow', 'Vista Hermosa');
insert into Clienti2 (id, nome, citta) values (43, 'Bethina Milroy', 'Verkhniy Mamon');
insert into Clienti2 (id, nome, citta) values (44, 'Salli Sandom', 'Marinići');
insert into Clienti2 (id, nome, citta) values (45, 'Reynold Enden', 'Payao');
insert into Clienti2 (id, nome, citta) values (46, 'Rooney Woodroofe', 'Ruše');
insert into Clienti2 (id, nome, citta) values (47, 'Marietta Rochford', 'Rueil-Malmaison');
insert into Clienti2 (id, nome, citta) values (48, 'Elisabetta Bratch', 'Tsagaan-Ovoo');
insert into Clienti2 (id, nome, citta) values (49, 'Catlaina Layman', 'Jaša Tomić');
insert into Clienti2 (id, nome, citta) values (50, 'Charmain Busk', 'Nanshe');
insert into Clienti2 (id, nome, citta) values (51, 'Artair McClenan', 'Yanfolila');
insert into Clienti2 (id, nome, citta) values (52, 'Jayne Vanne', 'Veyno');
insert into Clienti2 (id, nome, citta) values (53, 'Andriana Thorington', 'Ciwidara');
insert into Clienti2 (id, nome, citta) values (54, 'Maggie Ventom', 'Fundación');
insert into Clienti2 (id, nome, citta) values (55, 'Devonna Rodden', 'Dacudao');
insert into Clienti2 (id, nome, citta) values (56, 'Lizabeth Lipson', 'Rukaj');
insert into Clienti2 (id, nome, citta) values (57, 'Bond Ridgers', 'Lianyi');
insert into Clienti2 (id, nome, citta) values (58, 'Neda Jaffrey', 'Barili');
insert into Clienti2 (id, nome, citta) values (59, 'Lanita Barthorpe', 'Pilpichaca');
insert into Clienti2 (id, nome, citta) values (60, 'Frannie Bartos', 'Colomi');
insert into Clienti2 (id, nome, citta) values (61, 'Aubrey MacConneely', 'Gegernoong');
insert into Clienti2 (id, nome, citta) values (62, 'Lorita Langrish', 'Borek Wielkopolski');
insert into Clienti2 (id, nome, citta) values (63, 'Gan Bengefield', 'Okigwi');
insert into Clienti2 (id, nome, citta) values (64, 'Sax Ashbrook', 'Ampera');
insert into Clienti2 (id, nome, citta) values (65, 'Clovis Lisle', 'Kista');
insert into Clienti2 (id, nome, citta) values (66, 'Dilly Layman', 'Aygepat');
insert into Clienti2 (id, nome, citta) values (67, 'Dredi Gammage', 'Córdoba');
insert into Clienti2 (id, nome, citta) values (68, 'Alfy Bisset', 'Muang Phôn-Hông');
insert into Clienti2 (id, nome, citta) values (69, 'Emelda Glasebrook', 'Standerton');
insert into Clienti2 (id, nome, citta) values (70, 'Hew De Blasiis', 'Kupusina');
insert into Clienti2 (id, nome, citta) values (71, 'Hamilton Fishburn', 'Candelária');
insert into Clienti2 (id, nome, citta) values (72, 'Carola Bottomer', 'Cabouco');
insert into Clienti2 (id, nome, citta) values (73, 'Ardella Corbould', 'Ādīs Zemen');
insert into Clienti2 (id, nome, citta) values (74, 'Sadye Croucher', 'Sohag');
insert into Clienti2 (id, nome, citta) values (75, 'Shadow Dericot', 'Täby');
insert into Clienti2 (id, nome, citta) values (76, 'Tades Gladdish', 'Loga');
insert into Clienti2 (id, nome, citta) values (77, 'Reilly Gunda', 'Bualu');
insert into Clienti2 (id, nome, citta) values (78, 'Vanya Luc', 'Aveiro');
insert into Clienti2 (id, nome, citta) values (79, 'Launce Dudden', 'Colcabamba');
insert into Clienti2 (id, nome, citta) values (80, 'Marina Gorrie', 'Xishan');
insert into Clienti2 (id, nome, citta) values (81, 'Seth Mixhel', 'Kamiichi');
insert into Clienti2 (id, nome, citta) values (82, 'Rosalyn Huckerbe', 'La Huerta');
insert into Clienti2 (id, nome, citta) values (83, 'Thedric Grimsdike', 'Dongmafang');
insert into Clienti2 (id, nome, citta) values (84, 'Vern Banks', 'Paris 19');
insert into Clienti2 (id, nome, citta) values (85, 'Stephan Coggen', 'Jiesheng');
insert into Clienti2 (id, nome, citta) values (86, 'Pall Innocent', 'Kävlinge');
insert into Clienti2 (id, nome, citta) values (87, 'Maud Adanet', 'Lidingö');
insert into Clienti2 (id, nome, citta) values (88, 'Jordana Druitt', 'Grimshaw');
insert into Clienti2 (id, nome, citta) values (89, 'Ingar Borborough', 'Kalatongke');
insert into Clienti2 (id, nome, citta) values (90, 'Pearle McGready', 'Reuleuet');
insert into Clienti2 (id, nome, citta) values (91, 'Magdaia Gorden', 'Muricay');
insert into Clienti2 (id, nome, citta) values (92, 'Ryley Poolton', 'Guinoaliuan');
insert into Clienti2 (id, nome, citta) values (93, 'Jody Casbourne', 'Ujar');
insert into Clienti2 (id, nome, citta) values (94, 'Vera Londesborough', 'Lugo');
insert into Clienti2 (id, nome, citta) values (95, 'Rosette Lazer', 'Göteborg');
insert into Clienti2 (id, nome, citta) values (96, 'Annamarie Dummett', 'Reina Mercedes');
insert into Clienti2 (id, nome, citta) values (97, 'Beale Alloway', 'Kildare');
insert into Clienti2 (id, nome, citta) values (98, 'Yalonda Yeomans', 'Elimäki');
insert into Clienti2 (id, nome, citta) values (99, 'Marcia Maddocks', 'Roanoke');
insert into Clienti2 (id, nome, citta) values (100, 'Wilfrid Perocci', 'Mtubatuba');

create table Ordini (
	id INT,
	id_cliente INT,
	data_ordine DATE,
	importo DECIMAL(7,2)
);
insert into Ordini (id, id_cliente, data_ordine, importo) values (1, 7, '2025-08-14', 13126.61);
insert into Ordini (id, id_cliente, data_ordine, importo) values (2, 71, '2023-10-17', 23636.12);
insert into Ordini (id, id_cliente, data_ordine, importo) values (3, 93, '2025-09-24', 15128.15);
insert into Ordini (id, id_cliente, data_ordine, importo) values (4, 50, '2024-09-11', 65045.92);
insert into Ordini (id, id_cliente, data_ordine, importo) values (5, 24, '2023-05-21', 68963.67);
insert into Ordini (id, id_cliente, data_ordine, importo) values (6, 22, '2023-11-04', 58298.67);
insert into Ordini (id, id_cliente, data_ordine, importo) values (7, 92, '2025-05-21', 99775.63);
insert into Ordini (id, id_cliente, data_ordine, importo) values (8, 80, '2023-11-10', 71251.34);
insert into Ordini (id, id_cliente, data_ordine, importo) values (9, 36, '2024-09-23', 15385.83);
insert into Ordini (id, id_cliente, data_ordine, importo) values (10, 85, '2024-04-22', 4280.87);
insert into Ordini (id, id_cliente, data_ordine, importo) values (11, 77, '2024-11-19', 28510.9);
insert into Ordini (id, id_cliente, data_ordine, importo) values (12, 16, '2025-06-14', 2778.56);
insert into Ordini (id, id_cliente, data_ordine, importo) values (13, 58, '2026-01-04', 98268.36);
insert into Ordini (id, id_cliente, data_ordine, importo) values (14, 56, '2026-01-14', 67620.46);
insert into Ordini (id, id_cliente, data_ordine, importo) values (15, 64, '2025-03-28', 4650.44);
insert into Ordini (id, id_cliente, data_ordine, importo) values (16, 73, '2025-09-16', 25362.86);
insert into Ordini (id, id_cliente, data_ordine, importo) values (17, 93, '2024-02-20', 85055.64);
insert into Ordini (id, id_cliente, data_ordine, importo) values (18, 44, '2025-01-09', 68618.66);
insert into Ordini (id, id_cliente, data_ordine, importo) values (19, 57, '2025-07-28', 32448.54);
insert into Ordini (id, id_cliente, data_ordine, importo) values (20, 16, '2026-02-22', 31487.16);
insert into Ordini (id, id_cliente, data_ordine, importo) values (21, 79, '2024-10-11', 51365.1);
insert into Ordini (id, id_cliente, data_ordine, importo) values (22, 3, '2025-02-21', 77345.26);
insert into Ordini (id, id_cliente, data_ordine, importo) values (23, 1, '2026-01-22', 53648.94);
insert into Ordini (id, id_cliente, data_ordine, importo) values (24, 15, '2025-09-15', 24689.0);
insert into Ordini (id, id_cliente, data_ordine, importo) values (25, 53, '2024-12-22', 21679.45);
insert into Ordini (id, id_cliente, data_ordine, importo) values (26, 10, '2026-04-29', 7784.01);
insert into Ordini (id, id_cliente, data_ordine, importo) values (27, 49, '2026-02-18', 11977.18);
insert into Ordini (id, id_cliente, data_ordine, importo) values (28, 8, '2025-03-10', 99057.24);
insert into Ordini (id, id_cliente, data_ordine, importo) values (29, 4, '2025-10-25', 22135.92);
insert into Ordini (id, id_cliente, data_ordine, importo) values (30, 48, '2025-12-03', 88633.09);
insert into Ordini (id, id_cliente, data_ordine, importo) values (31, 34, '2026-04-09', 3618.38);
insert into Ordini (id, id_cliente, data_ordine, importo) values (32, 62, '2026-05-02', 96927.12);
insert into Ordini (id, id_cliente, data_ordine, importo) values (33, 89, '2023-12-26', 92493.46);
insert into Ordini (id, id_cliente, data_ordine, importo) values (34, 37, '2023-11-26', 22654.61);
insert into Ordini (id, id_cliente, data_ordine, importo) values (35, 46, '2024-08-14', 81520.11);
insert into Ordini (id, id_cliente, data_ordine, importo) values (36, 84, '2023-09-01', 56290.76);
insert into Ordini (id, id_cliente, data_ordine, importo) values (37, 14, '2026-04-15', 6245.79);
insert into Ordini (id, id_cliente, data_ordine, importo) values (38, 63, '2024-03-27', 21476.66);
insert into Ordini (id, id_cliente, data_ordine, importo) values (39, 66, '2024-02-26', 27717.31);
insert into Ordini (id, id_cliente, data_ordine, importo) values (40, 11, '2023-07-01', 75424.72);
insert into Ordini (id, id_cliente, data_ordine, importo) values (41, 43, '2023-12-21', 94157.63);
insert into Ordini (id, id_cliente, data_ordine, importo) values (42, 80, '2024-01-13', 86477.35);
insert into Ordini (id, id_cliente, data_ordine, importo) values (43, 30, '2025-10-05', 18375.6);
insert into Ordini (id, id_cliente, data_ordine, importo) values (44, 8, '2024-11-12', 57537.31);
insert into Ordini (id, id_cliente, data_ordine, importo) values (45, 28, '2023-11-22', 46523.06);
insert into Ordini (id, id_cliente, data_ordine, importo) values (46, 82, '2024-11-28', 85594.19);
insert into Ordini (id, id_cliente, data_ordine, importo) values (47, 96, '2025-12-07', 91079.43);
insert into Ordini (id, id_cliente, data_ordine, importo) values (48, 10, '2023-08-22', 58297.06);
insert into Ordini (id, id_cliente, data_ordine, importo) values (49, 43, '2024-05-29', 85413.63);
insert into Ordini (id, id_cliente, data_ordine, importo) values (50, 39, '2025-01-10', 69135.85);
insert into Ordini (id, id_cliente, data_ordine, importo) values (51, 95, '2024-10-03', 25930.56);
insert into Ordini (id, id_cliente, data_ordine, importo) values (52, 43, '2024-08-12', 22847.78);
insert into Ordini (id, id_cliente, data_ordine, importo) values (53, 55, '2026-05-04', 27586.11);
insert into Ordini (id, id_cliente, data_ordine, importo) values (54, 100, '2024-10-18', 98561.13);
insert into Ordini (id, id_cliente, data_ordine, importo) values (55, 100, '2023-07-09', 84521.92);
insert into Ordini (id, id_cliente, data_ordine, importo) values (56, 33, '2025-11-28', 27871.07);
insert into Ordini (id, id_cliente, data_ordine, importo) values (57, 42, '2025-11-05', 53160.55);
insert into Ordini (id, id_cliente, data_ordine, importo) values (58, 82, '2025-04-24', 75599.67);
insert into Ordini (id, id_cliente, data_ordine, importo) values (59, 81, '2024-03-07', 92687.55);
insert into Ordini (id, id_cliente, data_ordine, importo) values (60, 50, '2024-02-07', 18266.44);
insert into Ordini (id, id_cliente, data_ordine, importo) values (61, 6, '2025-08-26', 13027.2);
insert into Ordini (id, id_cliente, data_ordine, importo) values (62, 82, '2024-09-20', 21947.15);
insert into Ordini (id, id_cliente, data_ordine, importo) values (63, 19, '2024-10-18', 48141.19);
insert into Ordini (id, id_cliente, data_ordine, importo) values (64, 21, '2024-08-17', 54443.05);
insert into Ordini (id, id_cliente, data_ordine, importo) values (65, 69, '2025-09-15', 14219.13);
insert into Ordini (id, id_cliente, data_ordine, importo) values (66, 82, '2026-02-16', 48255.43);
insert into Ordini (id, id_cliente, data_ordine, importo) values (67, 98, '2023-12-20', 23903.83);
insert into Ordini (id, id_cliente, data_ordine, importo) values (68, 81, '2026-04-24', 31725.17);
insert into Ordini (id, id_cliente, data_ordine, importo) values (69, 49, '2024-08-01', 8977.78);
insert into Ordini (id, id_cliente, data_ordine, importo) values (70, 50, '2026-04-10', 69034.12);
insert into Ordini (id, id_cliente, data_ordine, importo) values (71, 73, '2025-10-27', 50045.04);
insert into Ordini (id, id_cliente, data_ordine, importo) values (72, 57, '2023-11-01', 76808.96);
insert into Ordini (id, id_cliente, data_ordine, importo) values (73, 80, '2024-08-07', 10146.51);
insert into Ordini (id, id_cliente, data_ordine, importo) values (74, 61, '2024-07-03', 53723.71);
insert into Ordini (id, id_cliente, data_ordine, importo) values (75, 14, '2025-08-11', 61813.85);
insert into Ordini (id, id_cliente, data_ordine, importo) values (76, 72, '2024-10-22', 83680.07);
insert into Ordini (id, id_cliente, data_ordine, importo) values (77, 18, '2025-08-28', 4709.32);
insert into Ordini (id, id_cliente, data_ordine, importo) values (78, 55, '2025-10-15', 60495.71);
insert into Ordini (id, id_cliente, data_ordine, importo) values (79, 6, '2023-11-27', 31872.0);
insert into Ordini (id, id_cliente, data_ordine, importo) values (80, 13, '2025-07-08', 97847.55);
insert into Ordini (id, id_cliente, data_ordine, importo) values (81, 98, '2023-11-25', 76641.82);
insert into Ordini (id, id_cliente, data_ordine, importo) values (82, 44, '2024-04-24', 37783.29);
insert into Ordini (id, id_cliente, data_ordine, importo) values (83, 83, '2024-02-08', 73494.74);
insert into Ordini (id, id_cliente, data_ordine, importo) values (84, 74, '2023-09-27', 60324.5);
insert into Ordini (id, id_cliente, data_ordine, importo) values (85, 73, '2023-12-24', 63202.17);
insert into Ordini (id, id_cliente, data_ordine, importo) values (86, 54, '2024-12-19', 13986.52);
insert into Ordini (id, id_cliente, data_ordine, importo) values (87, 36, '2024-01-13', 66923.87);
insert into Ordini (id, id_cliente, data_ordine, importo) values (88, 13, '2025-05-21', 3679.13);
insert into Ordini (id, id_cliente, data_ordine, importo) values (89, 82, '2025-05-20', 75459.38);
insert into Ordini (id, id_cliente, data_ordine, importo) values (90, 71, '2025-02-05', 83572.89);
insert into Ordini (id, id_cliente, data_ordine, importo) values (91, 24, '2025-10-16', 95418.3);
insert into Ordini (id, id_cliente, data_ordine, importo) values (92, 24, '2024-04-03', 82073.68);
insert into Ordini (id, id_cliente, data_ordine, importo) values (93, 18, '2024-02-23', 86316.26);
insert into Ordini (id, id_cliente, data_ordine, importo) values (94, 91, '2023-09-06', 81006.29);
insert into Ordini (id, id_cliente, data_ordine, importo) values (95, 75, '2025-05-03', 41263.09);
insert into Ordini (id, id_cliente, data_ordine, importo) values (96, 80, '2024-03-15', 13020.88);
insert into Ordini (id, id_cliente, data_ordine, importo) values (97, 31, '2025-12-30', 2071.6);
insert into Ordini (id, id_cliente, data_ordine, importo) values (98, 93, '2023-10-23', 5610.88);
insert into Ordini (id, id_cliente, data_ordine, importo) values (99, 45, '2023-06-09', 12472.0);
insert into Ordini (id, id_cliente, data_ordine, importo) values (100, 6, '2026-02-24', 96581.43);